### ISSUE TITLE
Uncaught Exception: Could not locate trait statement

### ISSUE THREAD

**Issue by karser** [psalm/phpunit-psalm-plugin#56]
It is unable to find `Symfony\Component\Validator\Test\ForwardCompatTestTrait`

```
 540 / 796 (67%)
░░░░Uncaught Exception: Could not locate trait statement
Stack trace in the forked worker:
#0 vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(114): Psalm\Internal\Codebase\ClassLikes->getTraitNode('Symfony\\Compone...')
#1 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1062): Psalm\PhpUnitPlugin\Hooks\TestCaseHandler::afterStatementAnalysis(Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Codebase), Array)
#2 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(201): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#3 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(318): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#4 vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(182): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(105, '')
#5 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(435): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#6 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#7 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false)
#8 vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check('', false)
#9 vendor/vimeo/psalm/psalm(2): require_once('')
#10 {main} in vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:339
Stack trace:
#0 vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(371): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(444): Psalm\Internal\Fork\Pool->wait()
#2 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#3 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false)
#4 vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check('', false)
#5 vendor/vimeo/psalm/psalm(2): require_once('')
#6 {main}
(Psalm 3.9.4@352bd3f5c5789db04e4010856c2f4e01ed354f4e crashed due to an uncaught Throwable)
```
Versions
```
psalm/plugin-phpunit: 0.9.0
vimeo/psalm: 3.9.4
weirdan/doctrine-psalm-plugin: 0.10.0
```

**Comment by weirdan** [comment]
Do you have a link to public repo that I can clone and reproduce the issue? 
Does Psalm crash with the phpunit plugin disabled on that same codebase?

If that ForwardCompatTrait  is anything like this: https://github.com/captainAldi/drupal-vue/blob/ae10e87dbe181a30751e0e6317b2f137e589118d/vendor/symfony/validator/Test/ForwardCompatTestTrait.php (horrible conditional eval abomination) it won't be easy to fix properly, but at least crashes could be prevented.

**Comment by karser** [comment]
>Do you have a link to public repo that I can clone and reproduce the issue?

No, it's private, unfortunately. I can try a PR against this codebase or change something in hooks/TestCaseHandler.php(114) if you suggest so.

>Does Psalm crash with the phpunit plugin disabled on that same codebase?

I disabled PhpUnitPlugin and the crash has gone

>If that ForwardCompatTrait is anything like this

That's correct, this file https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Test/ForwardCompatTestTrait.php

>it won't be easy to fix properly, but at least crashes could be prevented.

I started getting this crash after I updated from v3.8 to 3.9.4.

**Comment by weirdan** [comment]
@karser there's fresh new Psalm release (3.9.5) that might have fixed this issue.

**Comment by karser** [comment]
It is fixed, thank you!
